### ISSUE TITLE
Memory contents frame height does not update with memory size

### ISSUE THREAD

**Issue by TateThomas** [ngsorenson/UVSim#27]
When UVSim changes versions, the memory size changes, and the text frame for the memory also changes. The issue is, the scrollbar allows you to scroll down past the text frame.
![Screenshot 2024-04-09 195421](https://github.com/ngsorenson/UVSim/assets/106632630/3ba1e32d-4b6f-462f-990a-fd6e2f04d9cf)

**Comment by TateThomas** [comment]
Found more issues pertaining to this bug. For the same issue going the other way around (you have correct sizing for UVSim version 1, and you switch to version 2). This causes you to be unable to access memory after line 101 (see attached image. The bottom line is 101, but the scrollbar is at the bottom).

I found a slight fix, though. When you switch versions, the height will automatically update if you just try to resize the windows height. This also complicates things though, because it seems like it may just be a bug with tkinter or the framework we used to make the memory editor.

We could either just close this issue and update the documentation, saying that if you run into this issue, just try resizing the windows height, or we could actually attempt to fix this, but it seems like a pretty nasty bug.

![image](https://github.com/ngsorenson/UVSim/assets/106632630/dd6b04bf-1cc0-4303-b26a-8a9162239488)

**Comment by ngsorenson** [comment]
> Found more issues pertaining to this bug. For the same issue going the other way around (you have correct sizing for UVSim version 1, and you switch to version 2). This causes you to be unable to access memory after line 101 (see attached image. The bottom line is 101, but the scrollbar is at the bottom).

@TateThomas I'm not able to reproduce this. I load UVSim, switch to version 1 and see the original bug, switch back to version 2 and the memory window is all editable and exists down to 250. Does your local version of the code have the fix where the memory and cpu are being recreated when changing versions? I was having an issue like you describe before applying that fix while I was working on the paste bug.
