### ISSUE TITLE
Low priority: change version change prompt when importing file to buttons

### ISSUE THREAD

**Issue by TateThomas** [ngsorenson/UVSim#28]
Currently it asks for a yes or no answer (yes or y is accepted, same with no or n). It would be better to implement this with buttons. It could say something like 'This program appears to be a 4bit/6bit program, would you like to load it in UVSim version 1/2?' and have buttons saying 'yes' and 'no', or something similar to that. I didn't know how to implement a prompt with buttons.
![image](https://github.com/ngsorenson/UVSim/assets/106632630/9e7689cc-e584-4f6b-b826-0fb337544566)

**Comment by ngsorenson** [comment]
fixed in commit 032b278
