### ISSUE TITLE
update use cases/user stories

### ISSUE THREAD

**Issue by ngsorenson** [ngsorenson/UVSim#7]
"User stories and use cases look fine, although I think you upped the difficulty on yourselves unnecessarily -- some companies use one or the other, some use both, but they don't need to be tied together, where you are defining your use cases specifically off of a user story. The use cases are focused on functionality (and you got to the right level of detail) but can have "actors" that are not human (and don't need to be the same roles as discussed in the higher level user stories). You don't need to do anything now, but put it on your long-term TODO list for your final report in milestone 6 to revamp your use cases a little without needing to tie it educators and demonstrations, just use the program itself as the "actor" and describe the functionality and steps directly and you'll be good"

**Comment by TateThomas** [comment]
Assigned to @Tydidericksen
